language: node_js
node_js:
- node
sudo: false
script: gulp coverage
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: b9391e2a51755bb904a5e364acd9b6c07149bd1e4469902008e7e36fa26bd526
deploy:
  provider: npm
  email: stephen.austin@rovisys.com
  api_key:
    secure: B5WIAfe8Z01ORZR+6JwLydSByYG4mGNluNS3lop0mb8QWdFo7BI05qSA72rdx9i4zmi6IuBsSkgnd8n9YJeVvbbN0A1Rc+FL4bl+ml1NsKRgxbTPVtugsWDv8XIN/vNRznAILPEuT3i8Z5JY8Vcnqq7H6CObBpIXvAGkrX/pxZAW+DsFAwcFzZtyPXajCjCKUpKNTH0vvjYX61r/kljwCqdz2MRmzb00keIq47EXLW3ubo22hBVSFHm8+GGqKtWSQIh3pyhV2VgmZ05vHX5/gwSKoTZSXUyxsqRGffm9XT61QCYWlWys/SByefC1NCSfoMOihcZtUISNL/22tPgtpPGoQ1nKGUWpLKNunkm0YxmjK9jS4sWWNwWkmlrRYpMfPAcoHrfJMOGJyPvv//EFSNqSnUhTkRmZTK+JzzMSuMgLUYF0YHBQTA648aG0V7Tho9IdWUEbaczju/ehM5WrSnNLz4T7N1XRMJ3KuRt0o6yrb7r78AfpCldJY5LrKH8W4M3epF1g6pP6I1WgibuHe26X9fV8uMVBJmRAIw6bQMCQ7gQwsctFTlcq66JqcWtZij6EwDwOGbFb+q9RtR5ts0SM5eWtPT3T4iz1pmpwZU+pbfZFhqiKYDVz0pmKao5rDsHeswB1fLp0r6RkukfHrtrjWrsd58JcXDyHTc2wK/8=
  on:
    tags: true
    repo: RoviSys/react-style-decorator
