language: node_js
node_js:
- node
sudo: false
script:
- npm run test
- npm run coverage
- npm run build
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: b9391e2a51755bb904a5e364acd9b6c07149bd1e4469902008e7e36fa26bd526
deploy:
  provider: npm
  email: stephen.austin@rovisys.com
  api_key:
    secure: YSWOD3NYbr3UzmsSXOjfbVX/dG3jVduAXVNivCtt/1KJeEX4nYx5khX69NiTEQSkujEkLxi9rogvwiLPhqJM4SGQ51DjAYN44x26sN/Fdn4dlMh+ZNzL4B0klo75RY+HIMH6yOaKrSq9JlXvsZkvQfWFIgpNhYiiLIAQ0znY8ZrDq9lokKjh2+G7br+7yKWMxsxlmO1dJQa3sWKvwemD2vJrduLqIVY6ZGWd1WTv+Q74GLsbFjWOrc42t4SeoRRmJrMLAs/f2QNnQMCzwY13CQxszOhX/DjCo/QqJ9/2xRBQujUxmcrL0BJoGOw0+dliVgwIAUxwCQS4Hl7CxYFZutLFf299vXMfEjjvSGAp/6OHKA+LQfrbUWUPoFT9TZ2guzzyGOvrMP/PV04uqilcQLIDdy5IsrX17sfQHWQGQNgllo6ianmSxCgkmmHX2SXekVWAvw4qANWmB7FeQxnV+uyv0CgjFn13kXG+0bMrx3KPTlgpQCx+laRKrZ5Wu09mxYER/QoA7mkrh9iPurPZwc6a9GZLSmRQSR0Xdcw3LxQOmnNtaHKibS/DF/njh5iihIKF0WMMQ5SonBA9V3uqT7wuD3atnXmXkr97os1CTLLK/oMR27sDTyVExQa8xxloLS1/7HGig7IspzcJTlKnN54DNHLBaoU/n7jGENNqI7M=
  on:
    tags: true
    repo: RoviSys/react-style-decorator
